name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  win32: ^5.4.0
  firebase_core: ^3.5.0  # The latest version as required by cloud_firestore
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_21131.png
  - assets/images/logo.png
  - assets/images/electrician.png
  - assets/images/ACRepair.png
  - assets/images/ellipse_1013.png
  - assets/images/image_52.png
  - assets/images/rectangle_21132.png
  - assets/images/rectangle_2113.png
  - assets/images/rectangle_21134.png
  - assets/images/rectangle_21133.png
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/shape_6_x2.svg
  - assets/vectors/profile_major_1_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/shape_4_x2.svg
  - assets/vectors/inventory_major_113_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/shape_3_x2.svg
  - assets/vectors/shape_2_x2.svg
  - assets/images/ellipse_479.png
  - assets/images/ellipse_1013.png
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/images/solar_energy.png
  - assets/images/air_conditenior.png
  - assets/images/image_83.png
  - assets/images/image_831.png
  - assets/images/plumber.png
  - assets/images/multimeter.png
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/star_12_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/profile_major_110_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/star_125_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/icon_19_x2.svg
  - assets/vectors/filter_5_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/frame_3_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/images/avatar.png
  - assets/images/pngwing_com_1.png
  - assets/vectors/icon_21_x2.svg
  - assets/vectors/icon_34_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/filter_6_x2.svg
  - assets/vectors/icon_40_x2.svg
  - assets/vectors/icon_39_x2.svg
  - assets/vectors/icon_22_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/icon_36_x2.svg
  - assets/vectors/icon_41_x2.svg
  - assets/vectors/icon_20_x2.svg
  - assets/vectors/icon_17_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/images/ellipse_1013.png
  - assets/images/image_160.png
  - assets/images/rectangle_21133.png
  - assets/images/rectangle_21134.png
  - assets/images/rectangle_21131.png
  - assets/images/rectangle_2113.png
  - assets/images/rectangle_21132.png
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/shape_5_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/inventory_major_114_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/shape_7_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/shape_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/profile_major_111_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/shape_1_x2.svg
  - assets/images/avatar.png
  - assets/vectors/icon_23_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/vectors/icon_10_x2.svg
  - assets/vectors/icon_12_x2.svg
  - assets/vectors/icon_14_x2.svg
  - assets/vectors/filter_8_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/icon_32_x2.svg
  - assets/vectors/icon_4_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/icon_13_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/icon_16_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/images/solar_energy.png
  - assets/images/multimeter.png
  - assets/images/air_conditenior.png
  - assets/images/plumber.png
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/icon_9_x2.svg
  - assets/vectors/icon_44_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/profile_major_13_x2.svg
  - assets/vectors/frame_1_x2.svg
  - assets/vectors/filter_4_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_256_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_257_x2.svg
  - assets/images/plumber.png
  - assets/images/multimeter.png
  - assets/images/image_87.png
  - assets/images/image_831.png
  - assets/images/air_conditenior.png
  - assets/images/solar_energy.png
  - assets/images/image_83.png
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/union_4_x2.svg
  - assets/vectors/star_122_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/inventory_major_117_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/frame_5_x2.svg
  - assets/vectors/union_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/icon_26_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/profile_major_12_x2.svg
  - assets/vectors/star_121_x2.svg
  - assets/vectors/off_1_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/images/image_109.png
  - assets/images/image_113.png
  - assets/images/air_conditenior.png
  - assets/images/image_116.png
  - assets/images/image_114.png
  - assets/images/image_102.png
  - assets/images/image_112.png
  - assets/images/multimeter.png
  - assets/images/image_117.png
  - assets/images/image_108.png
  - assets/images/cctv.png
  - assets/images/image_104.png
  - assets/images/image_105.png
  - assets/images/image_1091.png
  - assets/images/image_100.png
  - assets/images/spin_mop.png
  - assets/images/image_103.png
  - assets/images/image_115.png
  - assets/images/car_waxing.png
  - assets/images/image_110.png
  - assets/images/laundry.png
  - assets/images/image_101.png
  - assets/images/image_111.png
  - assets/images/image_118.png
  - assets/vectors/inventory_major_115_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/profile_major_14_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/images/image_151.png
  - assets/images/image_152.png
  - assets/images/image_153.png
  - assets/images/image_84.png
  - assets/images/rectangle_2120.png
  - assets/images/rectangle_2118.png
  - assets/images/rectangle_21101.png
  - assets/images/rectangle_21102.png
  - assets/images/rectangle_2119.png
  - assets/images/rectangle_2117.png
  - assets/images/rectangle_2110.png
  - assets/vectors/star_152_x2.svg
  - assets/vectors/group_10000032952_x2.svg
  - assets/vectors/star_127_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/star_132_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/star_151_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/star_123_x2.svg
  - assets/vectors/star_142_x2.svg
  - assets/vectors/star_15_x2.svg
  - assets/vectors/star_131_x2.svg
  - assets/vectors/star_13_x2.svg
  - assets/vectors/star_14_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/group_1000003295_x2.svg
  - assets/vectors/star_124_x2.svg
  - assets/vectors/group_10000032951_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/star_141_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/images/image_3.png
  - assets/images/image.png
  - assets/images/image_5.png
  - assets/images/image_1.png
  - assets/images/image_2.png
  - assets/images/image_4.png
  - assets/vectors/icon_27_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/frame_4_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/profile_major_15_x2.svg
  - assets/vectors/filter_x2.svg
  - assets/vectors/icon_38_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/images/avatar.png
  - assets/images/pngwing_com_1.png
  - assets/vectors/icon_18_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/icon_1_x2.svg
  - assets/vectors/icon_37_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/icon_15_x2.svg
  - assets/vectors/icon_43_x2.svg
  - assets/vectors/icon_6_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/vectors/filter_1_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/icon_25_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/icon_42_x2.svg
  - assets/vectors/icon_11_x2.svg
  - assets/images/air_conditenior.png
  - assets/images/image_87.png
  - assets/images/plumber.png
  - assets/images/image_831.png
  - assets/images/solar_energy.png
  - assets/images/multimeter.png
  - assets/images/image_83.png
  - assets/vectors/star_126_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/filter_7_x2.svg
  - assets/vectors/star_128_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/profile_major_17_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/inventory_major_116_x2.svg
  - assets/vectors/frame_x2.svg
  - assets/images/image_4.png
  - assets/images/image.png
  - assets/images/image_5.png
  - assets/images/image_1.png
  - assets/images/image_2.png
  - assets/images/image_3.png
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/filter_2_x2.svg
  - assets/vectors/icon_24_x2.svg
  - assets/vectors/icon_31_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/frame_2_x2.svg
  - assets/vectors/profile_major_11_x2.svg
  - assets/vectors/vector_67_x2.svg

