name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  win32: ^5.4.0
  firebase_core: ^3.5.0  # The latest version as required by cloud_firestore
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_21131.png
  - assets/images/logo.png
  - assets/images/electrician.png
  - assets/images/ACRepair.png
  - assets/images/ellipse_1013.png
  - assets/images/image_52.png
  - assets/images/rectangle_21132.png
  - assets/images/rectangle_2113.png
  - assets/images/rectangle_21134.png
  - assets/images/rectangle_21133.png
  - assets/images/ellipse_479.png
  - assets/images/ellipse_1013.png
  - assets/images/solar_energy.png
  - assets/images/air_conditenior.png
  - assets/images/image_83.png
  - assets/images/image_831.png
  - assets/images/plumber.png
  - assets/images/multimeter.png
  - assets/images/avatar.png
  - assets/images/pngwing_com_1.png
  - assets/images/ellipse_1013.png
  - assets/images/image_160.png
  - assets/images/rectangle_21133.png
  - assets/images/rectangle_21134.png
  - assets/images/rectangle_21131.png
  - assets/images/rectangle_2113.png
  - assets/images/rectangle_21132.png
  - assets/images/avatar.png
  - assets/images/solar_energy.png
  - assets/images/multimeter.png
  - assets/images/air_conditenior.png
  - assets/images/plumber.png
  - assets/images/plumber.png
  - assets/images/multimeter.png
  - assets/images/image_87.png
  - assets/images/image_831.png
  - assets/images/air_conditenior.png
  - assets/images/solar_energy.png
  - assets/images/image_83.png
  - assets/images/image_109.png
  - assets/images/image_113.png
  - assets/images/air_conditenior.png
  - assets/images/image_116.png
  - assets/images/image_114.png
  - assets/images/image_102.png
  - assets/images/image_112.png
  - assets/images/multimeter.png
  - assets/images/image_117.png
  - assets/images/image_108.png
  - assets/images/cctv.png
  - assets/images/image_104.png
  - assets/images/image_105.png
  - assets/images/image_1091.png
  - assets/images/image_100.png
  - assets/images/spin_mop.png
  - assets/images/image_103.png
  - assets/images/image_115.png
  - assets/images/car_waxing.png
  - assets/images/image_110.png
  - assets/images/laundry.png
  - assets/images/image_101.png
  - assets/images/image_111.png
  - assets/images/image_118.png
  - assets/images/image_151.png
  - assets/images/image_152.png
  - assets/images/image_153.png
  - assets/images/image_84.png
  - assets/images/rectangle_2120.png
  - assets/images/rectangle_2118.png
  - assets/images/rectangle_21101.png
  - assets/images/rectangle_21102.png
  - assets/images/rectangle_2119.png
  - assets/images/rectangle_2117.png
  - assets/images/rectangle_2110.png
  - assets/images/image_3.png
  - assets/images/image.png
  - assets/images/image_5.png
  - assets/images/image_1.png
  - assets/images/image_2.png
  - assets/images/image_4.png
  - assets/images/avatar.png
  - assets/images/pngwing_com_1.png
  - assets/images/air_conditenior.png
  - assets/images/image_87.png
  - assets/images/plumber.png
  - assets/images/image_831.png
  - assets/images/solar_energy.png
  - assets/images/multimeter.png
  - assets/images/image_83.png
  - assets/images/image_4.png
  - assets/images/image.png
  - assets/images/image_5.png
  - assets/images/image_1.png
  - assets/images/image_2.png
  - assets/images/image_3.png


