// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFQ7Kdi-XoYokBVT38QBv-w1EXAUvuFQ',
    appId: '1:172279890522:web:e7fa01f948a458f5ebce63',
    messagingSenderId: '172279890522',
    projectId: 'quickfixapp-b6b4f',
    authDomain: 'quickfixapp-b6b4f.firebaseapp.com',
    storageBucket: 'quickfixapp-b6b4f.appspot.com',
    measurementId: 'G-GZYP29KXJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GPN0vQrwS_ANTr22lZ9UrL5o7BdxqcM',
    appId: '1:172279890522:android:fbf84b24bc0a7c47ebce63',
    messagingSenderId: '172279890522',
    projectId: 'quickfixapp-b6b4f',
    storageBucket: 'quickfixapp-b6b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5hmWC7FrcjCJzjge79EB-a7f8oKI3IA',
    appId: '1:172279890522:ios:a808b2b998a2c009ebce63',
    messagingSenderId: '172279890522',
    projectId: 'quickfixapp-b6b4f',
    storageBucket: 'quickfixapp-b6b4f.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc5hmWC7FrcjCJzjge79EB-a7f8oKI3IA',
    appId: '1:172279890522:ios:a808b2b998a2c009ebce63',
    messagingSenderId: '172279890522',
    projectId: 'quickfixapp-b6b4f',
    storageBucket: 'quickfixapp-b6b4f.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFQ7Kdi-XoYokBVT38QBv-w1EXAUvuFQ',
    appId: '1:172279890522:web:2654f2b0425eeadfebce63',
    messagingSenderId: '172279890522',
    projectId: 'quickfixapp-b6b4f',
    authDomain: 'quickfixapp-b6b4f.firebaseapp.com',
    storageBucket: 'quickfixapp-b6b4f.appspot.com',
    measurementId: 'G-HSHNYRHGNM',
  );
}
